spring:
  application:
      name: service-two
  profiles:
      active: dev
  kafka:
      consumer:
        auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

server:
  port: 8082

# logging:
#   level:
#     org.springframework: INFO
#     # Enable hibernate sql log
#     org.hibernate.SQL: DEBUG
#     # Log sql parameters. For Hibernate 5 version
#     org.hibernate.type.descriptor.sql: TRACE
#     # Log sql parameters. For Hibernate 6 version
# #    org.hibernate.orm.jdbc.bind: TRACE