spring:
  kafka:
    bootstrap-servers: kafka:9092
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
    defer-datasource-initialization: false

  datasource:
    url: jdbc:postgresql://postgres:5432/service_one_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
