spring:
  application:
      name: service-one
  profiles:
      active: dev
  kafka:
      consumer:
        auto-offset-reset: earliest
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        properties:
          spring.json.trusted.packages: "*"
      bootstrap-servers: localhost:9092
server:
  port: 8080

# This configuration ensures the Actuator’s /actuator/prometheus endpoint is exposed,
# providing a wealth of application metrics in a format that Prometheus can scrape.
management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

# logging:
#   level:
#     org.springframework: INFO
#     # Enable hibernate sql log
#     org.hibernate.SQL: DEBUG
#     # Log sql parameters. For Hibernate 5 version
#     org.hibernate.type.descriptor.sql: TRACE
#     # Log sql parameters. For Hibernate 6 version
# #    org.hibernate.orm.jdbc.bind: TRACE