spring:
  kafka:
    bootstrap-servers: localhost:9092

  datasource:
    url: jdbc:postgresql://localhost:5432/service_one_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

custom:
  service-two:
    url: http://localhost:8082/