spring:
  application:
      name: service-one
  profiles:
      active: dev
  kafka:
      consumer:
        auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

server:
  port: 8080

# This configuration ensures the Actuator’s /actuator/prometheus endpoint is exposed,
# providing a wealth of application metrics in a format that Prometheus can scrape.
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# logging:
#   level:
#     org.springframework: INFO
#     # Enable hibernate sql log
#     org.hibernate.SQL: DEBUG
#     # Log sql parameters. For Hibernate 5 version
#     org.hibernate.type.descriptor.sql: TRACE
#     # Log sql parameters. For Hibernate 6 version
# #    org.hibernate.orm.jdbc.bind: TRACE